### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by fernandes-natanael** [fga-eps-mds/2024.1-CALCULUS-DOC#51]
# Descrição
Faça a descrição da issue.

# Tarefas
Aba responsável por inserir as demandas desta issue.

- [ ] Tarefa 1
- [ ] Tarefa 2

# Critérios de Aceitação
O que foi concluído até o momento.
- [ ] Critério 1

# Informações Adicionais

**Comment by DaviMatheus** [comment]
Issue Concluida!!
