### ISSUE TITLE
Dojo de Backend

### ISSUE THREAD

**Issue by fernandes-natanael** [fga-eps-mds/2024.1-CALCULUS-DOC#6]
# Descrição
Nesta aula, vamos explorar os fundamentos do desenvolvimento backend, focando em conceitos básicos de linguagens de programação como Python, Node.js ou Java, e frameworks comumente usados, como Flask, Express ou Spring Boot. Esta será uma introdução para iniciantes, cobrindo os princípios básicos e as melhores práticas para criação de servidores e APIs.

# Tarefas
- [ ] Preparar material de estudo sobre uma linguagem de programação backend (por exemplo, Python, Node.js ou Java), abordando conceitos como variáveis, estruturas de controle, funções e manipulação de dados.
- [ ] Preparar material de estudo sobre um framework backend (por exemplo, Flask, Express ou Spring Boot), cobrindo tópicos como roteamento, manipulação de requisições HTTP e integração com bancos de dados.
- [ ] Criar exemplos práticos para demonstrar a criação de servidores e APIs usando a linguagem e o framework selecionados.
- [ ] Planejar exercícios práticos para os participantes aplicarem os conceitos aprendidos.

# Critérios de Aceitação
- [ ] Tarefa 1 concluída: Material de estudo sobre a linguagem de programação backend preparado.
- [ ] Tarefa 2 concluída: Material de estudo sobre o framework backend preparado.
- [ ] Tarefa 3 concluída: Exemplos práticos criados demonstrando a criação de servidores e APIs.
- [ ] Tarefa 4 concluída: Exercícios práticos planejados e prontos para serem distribuídos aos participantes.

# Informações Adicionais
Nenhuma.

**Comment by DaviMatheus** [comment]
Dojo realizado dia 21/07/2024

https://unbbr-my.sharepoint.com/:v:/g/personal/190058650_aluno_unb_br/EazdKvtpgepJlfcb5-Vy5LwBZBUvjfYcm8zyR1JM2t6HLw?referrer=Teams.TEAMS-WEB&referrerScenario=MeetingChicletGetLink.view
